"""empty message

Revision ID: 3175737fe508
Revises: None
Create Date: 2016-09-23 16:29:22.846253

"""

# revision identifiers, used by Alembic.
revision = '3175737fe508'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    ### end Alembic commands ###
