"""empty message

Revision ID: 4cc8222323cd
Revises: a021d45ae680
Create Date: 2016-09-27 18:24:49.839559

"""

# revision identifiers, used by Alembic.
revision = '4cc8222323cd'
down_revision = 'a021d45ae680'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pos', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pos', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    op.drop_table('racer')
    op.drop_table('position')
    op.drop_table('persons')
    ### end Alembic commands ###
