"""empty message

Revision ID: a021d45ae680
Revises: None
Create Date: 2016-09-27 18:03:25.530149

"""

# revision identifiers, used by Alembic.
revision = 'a021d45ae680'
down_revision = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zone')
    op.drop_table('persons')
    op.drop_table('racer')
    op.drop_table('position')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pos', geoalchemy2.types.Geometry(geometry_type=u'POINT'), autoincrement=False, nullable=True),
    sa.Column('accuracy', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'position_pkey')
    )
    op.create_table('racer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pos', geoalchemy2.types.Geometry(geometry_type=u'POINT'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'racer_pkey')
    )
    op.create_table('persons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'persons_pkey')
    )
    op.create_table('zone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type=u'POINT'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'zone_pkey')
    )
    ### end Alembic commands ###
