"""empty message

Revision ID: d10bd7644d06
Revises: ee0c71b55b3a
Create Date: 2016-09-25 12:54:17.702679

"""

# revision identifiers, used by Alembic.
revision = 'd10bd7644d06'
down_revision = 'ee0c71b55b3a'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_racer_pos', table_name='racer')
    op.drop_index('idx_zone_geom', table_name='zone')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_zone_geom', 'zone', ['geom'], unique=False)
    op.create_index('idx_racer_pos', 'racer', ['pos'], unique=False)
    ### end Alembic commands ###
